version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST:-db}
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    links:
      - db
    volumes:
      - $PWD:/home
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-docker}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  db:
    driver: local

networks:
  backend:
    driver: 'bridge'
